basePath: /
definitions:
  models.Employee:
    properties:
      createdAt:
        type: string
      department:
        type: string
      email:
        type: string
      employeeNumber:
        type: string
      firstName:
        type: string
      hireDate:
        type: string
      id:
        type: integer
      lastName:
        type: string
      position:
        type: string
      status:
        $ref: '#/definitions/models.EmployeeStatus'
      updatedAt:
        type: string
    type: object
  models.EmployeeStatus:
    enum:
    - ACTIVE
    - ON_VACATION
    - RETIRED
    type: string
    x-enum-varnames:
    - StatusActive
    - StatusOnVacation
    - StatusRetired
host: localhost:8081
info:
  contact:
    email: support@company.com
    name: API Support
  description: API for managing employees
  termsOfService: http://swagger.io/terms/
  title: Employee Management API
  version: "1.0"
paths:
  /employees:
    get:
      description: Retrieves all employees
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Employee'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all employees
      tags:
      - Employees
    post:
      consumes:
      - application/json
      description: Creates a new employee in the system
      parameters:
      - description: Employee data
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Employee'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new employee
      tags:
      - Employees
  /employees/{id}:
    delete:
      description: Deletes an employee by ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Employee deleted successfully
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete employee
      tags:
      - Employees
    get:
      description: Retrieves an employee by its ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Employee'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get employee by ID
      tags:
      - Employees
    put:
      consumes:
      - application/json
      description: Updates an existing employee
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated employee data
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.Employee'
      produces:
      - application/json
      responses:
        "204":
          description: Employee updated successfully
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update employee
      tags:
      - Employees
swagger: "2.0"
